version: "3.2"
services:
  server_consumer:
    build: server_consumer
    volumes:
      - "/Users/dbudonnyi/Documents/DiplomaKPI/bloom-filter-classificator/bloom_filter_classificator/server_consumer/server_consumer:/opt/server_consumer"
  client_producer:
    build: client_producer
    depends_on:
      - server_consumer 
    volumes:
      - "/Users/dbudonnyi/Documents/DiplomaKPI/bloom-filter-classificator/bloom_filter_classificator/client_producer/client_producer:/opt/client_producer"